----

# **Tenserflow Introduction**

## **Author**   :  **Muhammad Adil Naeem**

## **Contact**   :   **madilnaeem0@gmail.com**
<br>

----



### **Import Library**

In [1]:
import tensorflow as tf

### **Load Mnist Dataset**

In [3]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


### **Normalize the Dataset**

In [4]:
x_train, x_test = x_train / 255.0, x_test / 255.0

### **Create the model**

In [7]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


### **Predict For 1 value**

In [8]:
prediction = model(x_train[:1]).numpy()
prediction

array([[-0.49484217, -0.05647855,  0.7014748 ,  0.01157951,  0.36047474,
        -0.39623618,  0.2963574 , -0.645149  , -0.44844645,  0.7307182 ]],
      dtype=float32)

### **Convert these values into probability**

In [10]:
tf.nn.softmax(prediction).numpy()

array([[0.05407386, 0.0838236 , 0.17887156, 0.08972709, 0.1271882 ,
        0.05967762, 0.11928918, 0.04652753, 0.05664177, 0.1841796 ]],
      dtype=float32)

### **Create a Loss functiion for Our Model**

In [12]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], prediction).numpy()

2.818798

### **Compile Loss function**

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

### **Fit the Model**

In [14]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8576 - loss: 0.4851
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9557 - loss: 0.1517
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9677 - loss: 0.1097
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9743 - loss: 0.0864
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9770 - loss: 0.0755


### **Evaluate the Model**

In [15]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9773 - loss: 0.0734


[0.07343524694442749, 0.9772999882698059]

In [16]:
probality_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probality_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.1748594e-08, 1.6816211e-08, 6.5500135e-06, 1.5275923e-03,
        2.3551929e-12, 7.3995392e-07, 4.6910128e-12, 9.9846411e-01,
        7.0075941e-07, 2.4917503e-07],
       [9.2690022e-10, 1.1623834e-04, 9.9975210e-01, 3.4605408e-05,
        4.7956163e-17, 9.6177486e-05, 7.9868938e-09, 2.3263539e-13,
        8.8780132e-07, 2.2194882e-13],
       [4.1255899e-07, 9.9825829e-01, 2.2196783e-04, 3.2811273e-05,
        2.4291450e-05, 5.3564413e-06, 1.0309609e-05, 9.6362084e-04,
        4.8278688e-04, 2.3267030e-07],
       [9.9997723e-01, 5.4689182e-09, 5.4572770e-06, 2.1616411e-07,
        1.5489453e-08, 4.9824121e-06, 6.1924206e-06, 4.6790969e-06,
        6.0148002e-09, 1.2195111e-06],
       [3.4617115e-06, 6.1306480e-09, 7.4393215e-06, 1.6950889e-07,
        9.9709570e-01, 2.2638635e-06, 4.3806231e-06, 3.7569986e-05,
        3.3287176e-06, 2.8457225e-03]], dtype=float32)>